" Name:         enough-colors
" Description:  minimal colorscheme.
" Author:       ycm
" Maintainer:   ycm
" Website:      github.com/ycm
" License:      Public domain
" Last Change:  2024 Dec 03

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'enough'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = has('gui_running') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Removed diffRemoved
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#1e1e1e', '#ff0000', '#233223', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ebebeb', '#2d2d2d', '#b45a5a', '#6eb46e', '#b48c5a', '#82b4dc', '#b46eb4', '#64ffff', '#e0e0ed']
  endif
  if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
    hi Terminal guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#1e1e1e gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi CursorColumn guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#2d2d2d gui=NONE cterm=NONE
  hi CursorLineNr guifg=#646464 guibg=#1e1e1e gui=NONE cterm=NONE
  hi DiffAdd guifg=#ebebeb guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffChange guifg=#ebebeb guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffDelete guifg=#ebebeb guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffText guifg=#ebebeb guibg=#1e1e1e gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#82b4dc guibg=#1e1e1e gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi FoldColumn guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Folded guifg=#ebebeb guibg=#1e1e1e gui=italic cterm=italic
  hi IncSearch guifg=NONE guibg=#1e1e1e gui=standout cterm=reverse
  hi LineNr guifg=#646464 guibg=#1e1e1e gui=NONE cterm=NONE
  hi MatchParen guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi ModeMsg guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi MoreMsg guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi NonText guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Pmenu guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi PmenuSbar guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi PmenuSel guifg=#ebebeb guibg=#1e1e1e gui=reverse cterm=reverse
  hi PmenuThumb guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Question guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#373737 gui=NONE cterm=NONE
  hi SignColumn guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi SpecialKey guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi SpellBad guifg=#ebebeb guibg=#1e1e1e guisp=#ff0000 gui=NONE cterm=NONE
  hi SpellCap guifg=#ebebeb guibg=#1e1e1e guisp=#0000ff gui=NONE cterm=NONE
  hi SpellLocal guifg=#ebebeb guibg=#1e1e1e guisp=#ff00ff gui=NONE cterm=NONE
  hi SpellRare guifg=#ebebeb guibg=#1e1e1e guisp=#00ffff gui=reverse cterm=reverse
  hi StatusLine guifg=#ebebeb guibg=#373737 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi TabLine guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi TabLineFill guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi TabLineSel guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Title guifg=#6eb46e guibg=#1e1e1e gui=NONE cterm=NONE
  hi VertSplit guifg=#646464 guibg=#1e1e1e gui=NONE cterm=NONE
  hi Visual guifg=#ebebeb guibg=#373737 gui=NONE cterm=NONE
  hi VisualNOS guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi WarningMsg guifg=#b48c5a guibg=NONE gui=italic cterm=italic
  hi WildMenu guifg=#ebebeb guibg=#1e1e1e gui=NONE cterm=NONE
  hi Comment guifg=#646464 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#82b4dc guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#b45a5a guibg=NONE gui=italic cterm=italic
  hi Identifier guifg=#b48c5a guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#82b4dc guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#b46eb4 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#ebebeb guibg=NONE gui=underline cterm=underline
  hi! link Number Constant
  hi! link ErrorMsg Error
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#ebebeb gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ebebeb guibg=#1e1e1e gui=bold cterm=bold
  hi! link NERDTreeDirSlash Directory
  hi! link ALEVirtualTextWarning WarningMsg
  hi! link ALEWarningSign WarningMsg
  hi! link ALEVirtualTextError ErrorMsg
  hi! link ALEErrorSign ErrorMsg
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi Error gui=NONE cterm=NONE
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#53585f', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ebebeb', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#ffffff']
  endif
  if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#53585f guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
    hi Terminal guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#53585f gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi CursorColumn guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi CursorLine guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi CursorLineNr guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi DiffAdd guifg=#53585f guibg=#ebebeb gui=reverse cterm=reverse
  hi DiffChange guifg=#53585f guibg=#ebebeb gui=reverse cterm=reverse
  hi DiffDelete guifg=#53585f guibg=#ebebeb gui=reverse cterm=reverse
  hi DiffText guifg=#53585f guibg=#ebebeb gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi ErrorMsg guifg=#53585f guibg=#ebebeb gui=reverse cterm=reverse
  hi FoldColumn guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Folded guifg=#53585f guibg=#ebebeb gui=italic cterm=italic
  hi IncSearch guifg=#53585f guibg=#ebebeb gui=standout cterm=reverse
  hi LineNr guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi MatchParen guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi ModeMsg guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi MoreMsg guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi NonText guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Pmenu guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi PmenuSbar guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi PmenuSel guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi PmenuThumb guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Question guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Search guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi SignColumn guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi SpecialKey guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi SpellBad guifg=#53585f guibg=#ebebeb guisp=#ff0000 gui=NONE cterm=NONE
  hi SpellCap guifg=#53585f guibg=#ebebeb guisp=#0000ff gui=NONE cterm=NONE
  hi SpellLocal guifg=#53585f guibg=#ebebeb guisp=#ff00ff gui=NONE cterm=NONE
  hi SpellRare guifg=#53585f guibg=#ebebeb guisp=#00ffff gui=reverse cterm=reverse
  hi StatusLine guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi StatusLineNC guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi TabLine guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi TabLineFill guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi TabLineSel guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Title guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi VertSplit guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Visual guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi VisualNOS guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi WarningMsg guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi WildMenu guifg=#53585f guibg=#ebebeb gui=NONE cterm=NONE
  hi Comment guifg=#53585f guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#53585f guibg=#ebebeb gui=reverse cterm=reverse
  hi Identifier guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#53585f guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#53585f gui=NONE cterm=NONE
  hi ToolbarButton guifg=#53585f guibg=#ebebeb gui=bold cterm=bold
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=255 ctermbg=234 cterm=NONE
      hi Terminal ctermfg=255 ctermbg=234 cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=234 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=255 ctermbg=234 cterm=NONE
    hi CursorColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLineNr ctermfg=241 ctermbg=234 cterm=NONE
    hi DiffAdd ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffChange ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffDelete ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffText ctermfg=255 ctermbg=234 cterm=bold,reverse
    hi Directory ctermfg=110 ctermbg=234 cterm=NONE
    hi EndOfBuffer ctermfg=255 ctermbg=234 cterm=NONE
    hi FoldColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi Folded ctermfg=255 ctermbg=234 cterm=italic
    hi IncSearch ctermfg=NONE ctermbg=234 cterm=reverse
    hi LineNr ctermfg=241 ctermbg=234 cterm=NONE
    hi MatchParen ctermfg=255 ctermbg=234 cterm=NONE
    hi ModeMsg ctermfg=255 ctermbg=234 cterm=NONE
    hi MoreMsg ctermfg=255 ctermbg=234 cterm=NONE
    hi NonText ctermfg=255 ctermbg=234 cterm=NONE
    hi Pmenu ctermfg=255 ctermbg=234 cterm=NONE
    hi PmenuSbar ctermfg=255 ctermbg=234 cterm=NONE
    hi PmenuSel ctermfg=255 ctermbg=234 cterm=reverse
    hi PmenuThumb ctermfg=255 ctermbg=234 cterm=NONE
    hi Question ctermfg=255 ctermbg=234 cterm=NONE
    hi Search ctermfg=NONE ctermbg=237 cterm=NONE
    hi SignColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi SpecialKey ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellBad ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellCap ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellLocal ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellRare ctermfg=255 ctermbg=234 cterm=reverse
    hi StatusLine ctermfg=255 ctermbg=237 cterm=NONE
    hi StatusLineNC ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLine ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLineFill ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLineSel ctermfg=255 ctermbg=234 cterm=NONE
    hi Title ctermfg=71 ctermbg=234 cterm=NONE
    hi VertSplit ctermfg=241 ctermbg=234 cterm=NONE
    hi Visual ctermfg=255 ctermbg=237 cterm=NONE
    hi VisualNOS ctermfg=255 ctermbg=234 cterm=NONE
    hi WarningMsg ctermfg=137 ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=255 ctermbg=234 cterm=NONE
    hi Comment ctermfg=241 ctermbg=NONE cterm=italic
    hi Constant ctermfg=110 ctermbg=NONE cterm=NONE
    hi Error ctermfg=131 ctermbg=NONE cterm=italic
    hi Identifier ctermfg=137 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=131 ctermbg=NONE cterm=NONE
    hi Special ctermfg=110 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=131 ctermbg=NONE cterm=NONE
    hi String ctermfg=133 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=255 ctermbg=NONE cterm=NONE
    hi Type ctermfg=131 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=255 ctermbg=NONE cterm=underline
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi ToolbarButton ctermfg=255 ctermbg=234 cterm=bold
    hi! link NERDTreeDirSlash Directory
    hi! link ALEVirtualTextWarning WarningMsg
    hi! link ALEWarningSign WarningMsg
    hi! link ALEVirtualTextError ErrorMsg
    hi! link ALEErrorSign ErrorMsg
    if !s:italics
      hi Folded cterm=NONE
      hi WarningMsg cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
    endif
  else
    " Light background
    if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
      hi Normal ctermfg=240 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=240 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=240 ctermbg=255 cterm=NONE
      hi Terminal ctermfg=240 ctermbg=255 cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=240 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=240 ctermbg=255 cterm=NONE
    hi CursorColumn ctermfg=240 ctermbg=255 cterm=NONE
    hi CursorLine ctermfg=240 ctermbg=255 cterm=NONE
    hi CursorLineNr ctermfg=240 ctermbg=255 cterm=NONE
    hi DiffAdd ctermfg=240 ctermbg=255 cterm=reverse
    hi DiffChange ctermfg=240 ctermbg=255 cterm=reverse
    hi DiffDelete ctermfg=240 ctermbg=255 cterm=reverse
    hi DiffText ctermfg=240 ctermbg=255 cterm=bold,reverse
    hi Directory ctermfg=240 ctermbg=255 cterm=NONE
    hi EndOfBuffer ctermfg=240 ctermbg=255 cterm=NONE
    hi ErrorMsg ctermfg=240 ctermbg=255 cterm=reverse
    hi FoldColumn ctermfg=240 ctermbg=255 cterm=NONE
    hi Folded ctermfg=240 ctermbg=255 cterm=italic
    hi IncSearch ctermfg=240 ctermbg=255 cterm=reverse
    hi LineNr ctermfg=240 ctermbg=255 cterm=NONE
    hi MatchParen ctermfg=240 ctermbg=255 cterm=NONE
    hi ModeMsg ctermfg=240 ctermbg=255 cterm=NONE
    hi MoreMsg ctermfg=240 ctermbg=255 cterm=NONE
    hi NonText ctermfg=240 ctermbg=255 cterm=NONE
    hi Pmenu ctermfg=240 ctermbg=255 cterm=NONE
    hi PmenuSbar ctermfg=240 ctermbg=255 cterm=NONE
    hi PmenuSel ctermfg=240 ctermbg=255 cterm=NONE
    hi PmenuThumb ctermfg=240 ctermbg=255 cterm=NONE
    hi Question ctermfg=240 ctermbg=255 cterm=NONE
    hi Search ctermfg=240 ctermbg=255 cterm=NONE
    hi SignColumn ctermfg=240 ctermbg=255 cterm=NONE
    hi SpecialKey ctermfg=240 ctermbg=255 cterm=NONE
    hi SpellBad ctermfg=240 ctermbg=255 cterm=NONE
    hi SpellCap ctermfg=240 ctermbg=255 cterm=NONE
    hi SpellLocal ctermfg=240 ctermbg=255 cterm=NONE
    hi SpellRare ctermfg=240 ctermbg=255 cterm=reverse
    hi StatusLine ctermfg=240 ctermbg=255 cterm=NONE
    hi StatusLineNC ctermfg=240 ctermbg=255 cterm=NONE
    hi TabLine ctermfg=240 ctermbg=255 cterm=NONE
    hi TabLineFill ctermfg=240 ctermbg=255 cterm=NONE
    hi TabLineSel ctermfg=240 ctermbg=255 cterm=NONE
    hi Title ctermfg=240 ctermbg=255 cterm=NONE
    hi VertSplit ctermfg=240 ctermbg=255 cterm=NONE
    hi Visual ctermfg=240 ctermbg=255 cterm=NONE
    hi VisualNOS ctermfg=240 ctermbg=255 cterm=NONE
    hi WarningMsg ctermfg=240 ctermbg=255 cterm=NONE
    hi WildMenu ctermfg=240 ctermbg=255 cterm=NONE
    hi Comment ctermfg=240 ctermbg=NONE cterm=italic
    hi Constant ctermfg=240 ctermbg=NONE cterm=NONE
    hi Error ctermfg=240 ctermbg=255 cterm=reverse
    hi Identifier ctermfg=240 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=240 ctermbg=NONE cterm=NONE
    hi Special ctermfg=240 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=240 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=240 ctermbg=NONE cterm=NONE
    hi Type ctermfg=240 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=240 ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=240 cterm=NONE
    hi ToolbarButton ctermfg=240 ctermbg=255 cterm=bold
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=white ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=white ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=white ctermbg=Black cterm=NONE
      hi Terminal ctermfg=white ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=white ctermbg=Black cterm=NONE
    hi CursorColumn ctermfg=white ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi DiffAdd ctermfg=white ctermbg=Black cterm=reverse
    hi DiffChange ctermfg=white ctermbg=Black cterm=reverse
    hi DiffDelete ctermfg=white ctermbg=Black cterm=reverse
    hi DiffText ctermfg=white ctermbg=Black cterm=bold,reverse
    hi Directory ctermfg=LightBlue ctermbg=Black cterm=NONE
    hi EndOfBuffer ctermfg=white ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=white ctermbg=Black cterm=NONE
    hi Folded ctermfg=white ctermbg=Black cterm=italic
    hi IncSearch ctermfg=NONE ctermbg=Black cterm=reverse
    hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi MatchParen ctermfg=white ctermbg=Black cterm=NONE
    hi ModeMsg ctermfg=white ctermbg=Black cterm=NONE
    hi MoreMsg ctermfg=white ctermbg=Black cterm=NONE
    hi NonText ctermfg=white ctermbg=Black cterm=NONE
    hi Pmenu ctermfg=white ctermbg=Black cterm=NONE
    hi PmenuSbar ctermfg=white ctermbg=Black cterm=NONE
    hi PmenuSel ctermfg=white ctermbg=Black cterm=reverse
    hi PmenuThumb ctermfg=white ctermbg=Black cterm=NONE
    hi Question ctermfg=white ctermbg=Black cterm=NONE
    hi Search ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi SignColumn ctermfg=white ctermbg=Black cterm=NONE
    hi SpecialKey ctermfg=white ctermbg=Black cterm=NONE
    hi SpellBad ctermfg=white ctermbg=Black cterm=NONE
    hi SpellCap ctermfg=white ctermbg=Black cterm=NONE
    hi SpellLocal ctermfg=white ctermbg=Black cterm=NONE
    hi SpellRare ctermfg=white ctermbg=Black cterm=reverse
    hi StatusLine ctermfg=white ctermbg=DarkGrey cterm=NONE
    hi StatusLineNC ctermfg=white ctermbg=Black cterm=NONE
    hi TabLine ctermfg=white ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=white ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=white ctermbg=Black cterm=NONE
    hi Title ctermfg=LightGreen ctermbg=Black cterm=NONE
    hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Visual ctermfg=white ctermbg=DarkGrey cterm=NONE
    hi VisualNOS ctermfg=white ctermbg=Black cterm=NONE
    hi WarningMsg ctermfg=LightYellow ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=white ctermbg=Black cterm=NONE
    hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Error ctermfg=LightRed ctermbg=NONE cterm=italic
    hi Identifier ctermfg=LightYellow ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=white ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Special ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi String ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi Todo ctermfg=white ctermbg=NONE cterm=NONE
    hi Type ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=white ctermbg=NONE cterm=underline
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=white cterm=NONE
    hi ToolbarButton ctermfg=white ctermbg=Black cterm=bold
    hi! link NERDTreeDirSlash Directory
    hi! link ALEVirtualTextWarning WarningMsg
    hi! link ALEWarningSign WarningMsg
    hi! link ALEVirtualTextError ErrorMsg
    hi! link ALEErrorSign ErrorMsg
    if !s:italics
      hi Folded cterm=NONE
      hi WarningMsg cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
    endif
  else
    " Light background
    if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
      hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=Black ctermbg=LightGrey cterm=NONE
      hi Terminal ctermfg=Black ctermbg=LightGrey cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi CursorColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi CursorLine ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi DiffAdd ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi DiffChange ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi DiffDelete ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi DiffText ctermfg=Black ctermbg=LightGrey cterm=bold,reverse
    hi Directory ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi EndOfBuffer ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi ErrorMsg ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi FoldColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Folded ctermfg=Black ctermbg=LightGrey cterm=italic
    hi IncSearch ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi LineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi MatchParen ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi MoreMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi NonText ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuSbar ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuThumb ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Question ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Search ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SignColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SpecialKey ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SpellBad ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SpellCap ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SpellLocal ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi SpellRare ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi StatusLineNC ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Title ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi VertSplit ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Visual ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi VisualNOS ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi WarningMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Comment ctermfg=Black ctermbg=NONE cterm=italic
    hi Constant ctermfg=Black ctermbg=NONE cterm=NONE
    hi Error ctermfg=Black ctermbg=LightGrey cterm=reverse
    hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=Black ctermbg=NONE cterm=NONE
    hi Special ctermfg=Black ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Black ctermbg=NONE cterm=NONE
    hi Todo ctermfg=Black ctermbg=NONE cterm=NONE
    hi Type ctermfg=Black ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Black ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
    hi ToolbarButton ctermfg=Black ctermbg=LightGrey cterm=bold
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                rgb( 30,  30,  30)     ~        Black
" Color: red                  rgb(255,   0,   0)     ~        DarkRed
" Color: green                rgb( 35,  50,  35)     ~        DarkGreen
" Color: yellow               rgb(255, 255,   0)     ~        DarkYellow
" Color: blue                 rgb(  0,   0, 255)     ~        DarkBlue
" Color: magenta              rgb(255,   0, 255)     ~        DarkMagenta
" Color: cyan                 rgb(  0, 255, 255)     ~        DarkCyan
" Color: white                rgb(235, 235, 235)     ~        white
" Color: brightblack          rgb( 45,  45,  45)     ~        DarkGrey
" Color: brightred            rgb(180,  90,  90)     ~        LightRed
" Color: brightgreen          rgb(110, 180, 110)     ~        LightGreen
" Color: brightyellow         rgb(180, 140,  90)     ~        LightYellow
" Color: brightblue           rgb(130, 180, 220)     ~        LightBlue
" Color: brightmagenta        rgb(180, 110, 180)     ~        LightMagenta
" Color: brightcyan           rgb(100, 255, 255)     ~        LightCyan
" Color: brightwhite          #e0e0ed                231      white
" Color: midgrey              rgb( 55,  55,  55)     ~        DarkGrey
" Color: brightgrey           rgb(100, 100, 100)     ~        LightGrey
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: light
" Color: black                rgb( 83,  88,  95)     ~        Black
" Color: red                  rgb(255,   0,   0)     ~        DarkRed
" Color: green                rgb(  0, 255,   0)     ~        DarkGreen
" Color: yellow               rgb(255, 255,   0)     ~        DarkYellow
" Color: blue                 rgb(  0,   0, 255)     ~        DarkBlue
" Color: magenta              rgb(255,   0, 255)     ~        DarkMagenta
" Color: cyan                 rgb(  0, 255, 255)     ~        DarkCyan
" Color: white                rgb(235, 235, 235)     ~        LightGrey
" Color: brightblack          rgb(210, 210, 210)     ~        DarkGrey
" Color: brightred            rgb(255, 100,   0)     ~        LightRed
" Color: brightgreen          rgb(100, 255,   0)     ~        LightGreen
" Color: brightyellow         rgb(255, 255, 100)     ~        LightYellow
" Color: brightblue           rgb(  0, 100, 255)     ~        LightBlue
" Color: brightmagenta        rgb(255, 100, 255)     ~        LightMagenta
" Color: brightcyan           rgb(100, 255, 255)     ~        LightCyan
" Color: brightwhite          #ffffff                231      white
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
